ALTER TABLE `book_author` ADD `original_name` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '本名', 
ADD `hometown` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '籍貫',
ADD `birth_year` CHAR(4) NOT NULL DEFAULT '' COMMENT '出生年',
ADD `birth_month` CHAR(2) NOT NULL DEFAULT '' COMMENT '出生月',
ADD `bitrh_day` CHAR(2) NOT NULL DEFAULT '' COMMENT '出生日',
ADD `arrive_time` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '來台時間',
ADD `experience` TEXT NOT NULL DEFAULT '' COMMENT '學經歷',
ADD `literary_style` TEXT NOT NULL DEFAULT '' COMMENT '文學風格',
ADD `literary_achievement` TEXT NOT NULL DEFAULT '' COMMENT '文學成就(得獎經歷)',
ADD `year_of_death` CHAR(4) NOT NULL DEFAULT '' COMMENT '卒年',
ADD `year_of_month` CHAR(2) NOT NULL DEFAULT '' COMMENT '卒月',
ADD `year_of_day` CHAR(4) NOT NULL DEFAULT '' COMMENT '卒日',
ADD `pen_name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '筆名',
ADD `literary_genre` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '創作文類',
ADD `present_job` TEXT NOT NULL DEFAULT '' COMMENT '現職',
ADD `brief_intro` TEXT NOT NULL DEFAULT '' COMMENT '簡介';
