version: '3.1'
services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_NAME=wenhsun_hr
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    logging:
      options:
        max-size: "200M"
        max-file: "2"
  db:
    image: mysql:latest
    command:
      - "--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      - "--default-authentication-plugin=mysql_native_password"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wenhsun
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "33061:3306"
    logging:
      options:
        max-size: "200M"
        max-file: "2"
